### PR TITLE
Revert unwanted removals from previous PR #99

### PR DESCRIPTION
**Pull request by florian-h05**
This reverts the removal of `time.ZonedDateTime.millisFromNow()` and
Timer docs from the README from PR #99.

Signed-off-by: Florian Hotze <florianh_dev@icloud.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
Hi @florian-h05  i fixed  just merged #101 which has now caused conflicts here, can you fix those and i will merge this?  Then we can look at formatting the code base in #107

**Comment by digitaldan** [comment]
Hi @florian-h05  i fixed  just merged #101 which has now caused conflicts here, can you fix those and i will merge this?  Then we can look at formatting the code base in #107

**Comment by florian-h05** [comment]
@digitaldan 
Should be ready to merge now.

**Review by digitaldan — APPROVED** [review]
LGTM!

**Pull request merged**
