### PR TITLE
Typos a/an

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
LGTM, can you please regenerate the type definitions and commit them? `npm run types`

**Comment by florian-h05** [comment]
And please sign off your commits, otherwise I cannot merge them. 
https://github.com/openhab/openhab-js/pull/277/checks?check_run_id=14820783373 gives advice how to sign off your existing commits, or just comment your sign off here.

**Comment by dilyanpalauzov** [comment]
I am not going to add a sign-off line, since in my eyes this has no added value.

**Comment by florian-h05** [comment]
I have checked your other a/an typos, seems like they applied the exception, so I will make the same exception here.

Note that it does not matter for any one whether the sign off has an added value or not, it is a rule several open-source projects have and openHAB has as well: https://www.openhab.org/docs/developer/contributing.html#sign-your-work.

**Pull request merged**
