### PR TITLE
[items] ItemHistory: Change return types of min/max between/since to number

### PR DESCRIPTION
**Pull request by florian-h05**
Changes the return types of `ItemHistory.`
- `maximumBetween`
- `maximumSince`
- `minimumBetween`
- `minimumSince`

from string to number.

Possibly breaking.

### CODE REVIEW

**Comment by florian-h05** [comment]
@jpg0 Can you review?

**Comment by jpg0** [comment]
> @jpg0 Can you review?

Could you add into the function descriptions what the units of then returned numbers are? I would hope/expect they match the units of the parameters.

**Comment by florian-h05** [comment]
> I would hope/expect they match the units of the parameters.

Not sure what you mean with this.

> what the units of then returned numbers are?

The units would be could of, but I think that the current code wouldn’t even work. I’ll test this later.

I am wondering if we shouldn’t introduce a library for UoM handling like https://github.com/gentooboontoo/js-quantities? WDYT?

**Comment by jpg0** [comment]
Personally I don't believe that we should introduce a units library, at least not yet.

I just wanted to ensure that the return units are easily handled in JS - for example they are milliseconds. I'm not sure what they are from the code/docs.

**Comment by florian-h05** [comment]
> I just wanted to ensure that the return units are easily handled in JS - for example they are milliseconds. I'm not sure what they are from the code/docs.

It seems that:
- for Items from bindings without UoM, just the value is returned, sometimes together with the unit from the Item's state description.
- for Items from bindings with UoM, it seems that the base unit is used (so Wh instead of kWh).

But I'm not sure.

**Comment by florian-h05** [comment]
@jpg0 Are you fine with my little addition to the docs regarding the units?

**Comment by florian-h05** [comment]
@jpg0
I've just noticed that either number or NaN is returned, so either I correct the JSDoc or I modify the function to return number or null as all other functions do.

What would you prefer?

**Comment by jpg0** [comment]
If the other functions return null, then let's keep with that.

**Pull request merged**
