### PR TITLE
[items & things] Add `toString` overrides & Clean-Ups

### PR DESCRIPTION
**Pull request by florian-h05**
Reference #197 (fixes the JS library side).

## To Dos

- [x] Regenerate type definitions
- [x] Update CHANGELOG

### CODE REVIEW

**Comment by florian-h05** [comment]
@jpg0 Can I remove thing builder and channel builder here?

**Comment by jpg0** [comment]
> @jpg0 Can I remove thing builder and channel builder here?

Are they used? I don't mind whether they go or stay, I suppose it depends on the purpose of the library. I used them to define and register things and channels in scripts (and then refer to them from other scripts). I did this to move all my configuration into JS, and then could reference everything via JS imports instead of name strings.

However if this library is limited to rules based on existing definitions, then this functionality should be removed.

Maybe @digitaldan has an opinion?

**Comment by digitaldan** [comment]
> Maybe @digitaldan has an opinion?

I would error on the side of simplicity. Since it's undocumented and probably unused by most, i think removing it makes sense.

**Comment by florian-h05** [comment]
So we agree that we remove that?

Can one of you please review here (although the changes apart from the removal are minimal).

**Comment by florian-h05** [comment]
@jpg0 Can you please review here? You can ignore the `*.d.ts` files, these type definitions are auto generated.

**Review by digitaldan — APPROVED** [review]
LGTM!

**Pull request merged**
