### PR TITLE
[trigger] Add `GenericEventTrigger`

### PR DESCRIPTION
**Pull request by mjcumming**
<!--
Thanks for contributing to the openHAB project!

Expand trigger events in JavaScript

# Generic Event Trigger
- [triggers] Adds the GenericEventTrigger to types of events that JS can use.

# Description

Add the core.GenericEventTrigger

# Testing

rules.JSRule({
    name: "Item State Changed Events",
    description: "Triggers when any item state changes",
    triggers: [GenericEventTrigger("openhab/items/**","","ItemStateChangedEvent","AllItemStateEvents")],
    execute: (event) => {
        console.log ("Item State Changed Event: ",event)
    },
    tags: ["ItemStateChanged"],
    id: "ItemStateChanged"
});

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
Thanks for your PR!

I have fixed the lint and your code issues (missing comma in the exports, array was not accepted) and improved your JSDoc.
I also re-regenerated the type defs.

Please have a look at https://github.com/openhab/openhab-js/blob/main/DEPLOY.md and https://github.com/openhab/openhab-js/blob/main/CONTRIBUTING.md

BTW: Creating a PR from your main branch is not so good, because you can run into issues when you try to update your main branch for future contributions. Always use feature branches when working on a fork!

**Comment by mjcumming** [comment]
> Thanks for your PR!
> 
> I have fixed the lint and your code issues (missing comma in the exports, array was not accepted) and improved your JSDoc. I also re-regenerated the type defs.
> 
> Please have a look at https://github.com/openhab/openhab-js/blob/main/DEPLOY.md and https://github.com/openhab/openhab-js/blob/main/CONTRIBUTING.md
> 
> BTW: Creating a PR from your main branch is not so good, because you can run into issues when you try to update your main branch for future contributions. Always use feature branches when working on a fork!

Hi, thank you for merging. I'm not well versed in doing PR's and git. I review the links for next time! Mike

**Comment by florian-h05** [comment]
In general, all you need to do is `npm run lint:fix` to lint your code and fix problems, and once you are finished, run `npm run types` to update the type defs.
Or run `npm run deploy`, which will lint (but not fix), and also perform various tests.

**Comment by florian-h05** [comment]
BTW when reviewing this PR I found a bug in openhab-core, which broke the `eventSource`.
I submitted a fix https://github.com/openhab/openhab-core/pull/3837, which already got merged.

Letting you know in case you run into that problem. The fix will be available in the latest snapshot(s) or in Milestone 3 and above (not released yet).

**Comment by mjcumming** [comment]
That explains why I couldn't use the eventSource to filter... :)  Thank you for the npm hints.

Mike

**Pull request merged**
