### PR TITLE
[items] ItemPersistence: Convert state to primitive type in `persist` method

### PR DESCRIPTION
**Pull request by florian-h05**
This fixes an issue, where the asynchronous way persistence services store the passed in state causes a IllegalStateException by GraalJS, because multithreaded access to the script's context is not allowed.

See https://github.com/openhab/openhab-core/pull/4268#issuecomment-2150493510.

### CODE REVIEW

**Comment by florian-h05** [comment]
@jlaur Can you please check if this fixes the issue?

Run `npm i git+https://github.com/florian-h05/openhab-js.git#persist-toopenhabprimitivetype` inside the `automation/js` folder and disable injection caching in the add-on settings.

**Comment by jlaur** [comment]
> Can you please check if this fixes the issue?

Sure. I'll have a look asap. Will need to figure out how to do this in Windows where I have my development installation.

**Comment by florian-h05** [comment]
In case you can’t figure it out I can provide you the webpacked version of the library (this is a single file containing the „compiled“ library and dependency code) tomorrow so you can simply download it and put it into the node_modules folder.

**Comment by jlaur** [comment]
> In case you can’t figure it out I can provide you the webpacked version of the library (this is a single file containing the „compiled“ library and dependency code) tomorrow so you can simply download it and put it into the node_modules folder.

Thanks. I remembered that I have a (very old) WSL installation on my Windows machine, so I'm currently updating it and will see if I can install nodejs there. Will continue tomorrow and let you know. 🙂

**Comment by jlaur** [comment]
> Thanks. I remembered that I have a (very old) WSL installation on my Windows machine, so I'm currently updating it and will see if I can install nodejs there. Will continue tomorrow and let you know. 🙂

That went smoother than expected. I was able to install nodejs and npm after the upgrade, and your `npm` command worked as well. I have now tested it before and after switching to your new version. I started by reproducing it with the injected version, and after switching to the new version, the exception no longer occurred, and all items were persisted correctly. 👍

**Pull request merged**
