### PR TITLE
Add standardx to enforce consistent codestyle

### PR DESCRIPTION
**Pull request by florian-h05**
# Add `standardx` to enforce consistent codestyle

# Description
This PR adds `standardx` (you might also know the JavaScript [`standard`](https://standardjs.com) or `semistandard` libraries) to enforce a consistent codestyle.
I decided for `standardx` as it is based on `standard`, which is widely used, and is also highly customizable as it is based on `eslint`.
The codestyle is checked every time `npm test` runs, therefore it would also apply to the jobs that run on a PR.

My motivation for this was, that the codestyle here often differs, e.g. the intendation.
I have applied the codestyle to all JavaScript files.

# Testing

I have never experienced any problems with the automated fix function of StandardJS and currently I am testing this PR on my system.
But as I do not use everything the library provides, maybe somebody could also test it.

You can find the packed tarball here: https://1drv.ms/u/s!Al8cKKxosMjV7goODVlLcCvpB-aM?e=lDM9PJ

@digitaldan 
Please let me know what you think about that addition / change.

### CODE REVIEW

**Comment by digitaldan** [comment]
Thanks florian, i think this is a great idea.  If you can update the PR to resolve conflicts I'll take a look at it locally.

**Comment by florian-h05** [comment]
@digitaldan 
All conflicts are resolved!

**Comment by florian-h05** [comment]
@digitaldan 
Have you had a look at it yet?

**Comment by digitaldan** [comment]
Hey @florian-h05 i'm looking at oh stuff today, i'll give this a spin today.

**Comment by digitaldan** [comment]
So this looks good to me!  Lets get #99 and #101 merged fist so we don't have conflicts and then we can merge this one.

**Comment by florian-h05** [comment]
@digitaldan
Before this gets merged, I will rebase from main and re-apply the code formatting to resolve all conflicts.

**Comment by digitaldan** [comment]
Ok, i think we are ready if you want to rebase and re-apply.

**Comment by florian-h05** [comment]
@digitaldan 
I rebased and reapplied the linting, ready to go now!

**Comment by digitaldan** [comment]
👍

**Pull request merged**
