### PR TITLE
Add markdownlint & broken link check

### PR DESCRIPTION
**Pull request by florian-h05**
This PR adds `markdownlint` and the broken link check from the openhab-docs repo.

### CODE REVIEW

**Comment by florian-h05** [comment]
@digitaldan 
I‘ll update this as it includes my commits from PR #154, then this is ready from my side.

**Comment by florian-h05** [comment]
@digitaldan 
This ready for merging now.

**Comment by florian-h05** [comment]
@digitaldan
Any chance of merging this weekend?

**Review by digitaldan — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
