### PR TITLE
[actions] Add Transformation Actions as a class & Add arg type checking lib

### LINKED ISSUE #100: [docs] Transformation action is missing
All the core Actions are imported in `actions.js` except for Transformation. We should include all the core Actions.

I'll submit a PR in the next couple of days but is someone wants to run with this please do. It's only one line of code and a few lines of docs strings.

## Your Environment

* Version used: latest as of this writing

### PR DESCRIPTION
**Pull request by florian-h05**
Fixes #100.

## Description

- Adds the Transformation actions to the README.
- Explicitely adds the Transformation actions as a class to provide type defs, JSDoc and arg type checking.
- Adds the `typeof-arguments` module to allow easy type checking of function arguments (reference also to https://github.com/openhab/openhab-js/issues/176)

Bundle-size increases from 852 KB to 868 KB, which is really not much.

### CODE REVIEW

**Comment by florian-h05** [comment]
@jpg0 Can you review?

**Comment by florian-h05** [comment]
@digitaldan @jpg0 Can one of you please review so we can get this merged before the 3.4.0 feature freeze?

**Comment by jpg0** [comment]
I would prefer that the Transformation class is pulled out into it's own file, but whatever, that can be done later.

**Comment by jpg0** [comment]
Does the failing check matter here? I don't know how the docs system works.

**Comment by florian-h05** [comment]
> Does the failing check matter here? I don't know how the docs system works.

In this case, no I expect that failure. It is caused, because I reference the JSDoc for the Transformation class from the README. The JSDoc it references is not available online yet, it will be when this PR is merged and JSDoc updates.

**Comment by florian-h05** [comment]
@jpg0 Can we merge then?

**Review by digitaldan — APPROVED** [review]
LGTM

**Comment by jpg0** [comment]
FYI the inverse of this work: transformations using ES6 - has not yet been implemented, and still uses Nashorn.

**Comment by florian-h05** [comment]
You refer to the JavaScript Transformation service, right?
I am aware that it is still using Nashorn, the question is if we need to replace it with a new Transformation service addon, or if using https://github.com/openhab/openhab-core/pull/2883 is fine.

**Comment by jpg0** [comment]
Oh wow, there's lots of progress there that I wasn't aware of. Thanks for the pointer.

**Comment by florian-h05** [comment]
@jpg0 
There are also docs for this (added today): https://github.com/openhab/openhab-docs/pull/1940.

I’ll add a section to our README to document the usage of JS Scripting for transformations.

**Pull request merged**
